name: smartpot
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.13.0 # Version à vérifier selon la dernière disponible
  firebase_analytics: ^11.4.5 # Version à vérifier selon la dernière disponible
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter lints for best practices
  flutter_lints: ^5.0.0

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets section (Uncomment and add assets if you need them)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts section (Uncomment and add custom fonts if you need them)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
  - family: FredokaOne
    fonts:
      - asset: assets/fonts/FredokaOne-Regular.ttf
