// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvzOtubZuI4dN_roYFrC2lAGfcgBttYw',
    appId: '1:24633911044:web:61d31dfaf8d1a201019251',
    messagingSenderId: '24633911044',
    projectId: 'smartpot-3d8a5',
    authDomain: 'smartpot-3d8a5.firebaseapp.com',
    databaseURL: 'https://smartpot-3d8a5-default-rtdb.firebaseio.com',
    storageBucket: 'smartpot-3d8a5.firebasestorage.app',
    measurementId: 'G-SSC9YD7K8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCCyikj0guQv9aQ7ohwBxNWtqoF9dWeM',
    appId: '1:24633911044:android:c49540283890d00d019251',
    messagingSenderId: '24633911044',
    projectId: 'smartpot-3d8a5',
    databaseURL: 'https://smartpot-3d8a5-default-rtdb.firebaseio.com',
    storageBucket: 'smartpot-3d8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNc7O6inL0eAI4xPFpMYjcV07M8hExm00',
    appId: '1:24633911044:ios:1f9a06528df2a6bb019251',
    messagingSenderId: '24633911044',
    projectId: 'smartpot-3d8a5',
    databaseURL: 'https://smartpot-3d8a5-default-rtdb.firebaseio.com',
    storageBucket: 'smartpot-3d8a5.firebasestorage.app',
    iosBundleId: 'com.example.smartpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNc7O6inL0eAI4xPFpMYjcV07M8hExm00',
    appId: '1:24633911044:ios:1f9a06528df2a6bb019251',
    messagingSenderId: '24633911044',
    projectId: 'smartpot-3d8a5',
    databaseURL: 'https://smartpot-3d8a5-default-rtdb.firebaseio.com',
    storageBucket: 'smartpot-3d8a5.firebasestorage.app',
    iosBundleId: 'com.example.smartpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArvzOtubZuI4dN_roYFrC2lAGfcgBttYw',
    appId: '1:24633911044:web:ca309479a6ae633e019251',
    messagingSenderId: '24633911044',
    projectId: 'smartpot-3d8a5',
    authDomain: 'smartpot-3d8a5.firebaseapp.com',
    databaseURL: 'https://smartpot-3d8a5-default-rtdb.firebaseio.com',
    storageBucket: 'smartpot-3d8a5.firebasestorage.app',
    measurementId: 'G-88HGKXDJQ7',
  );
}
